using Shoko.VFS.FUSE.Models;

namespace Shoko.VFS.FUSE.Resolvers;

/// <summary>
/// Supplies the pre-resolved Shoko data used by a path resolver.
/// Adapters are responsible for caching data returned by Shoko.
/// </summary>
public interface IShokoPathDataSource
{
    /// <summary>
    /// Gets all series and their episode/file mappings.
    /// Consumers that need mutable data may call this method again.
    /// </summary>
    IReadOnlyList<SeriesData> GetAllSeries();
}

/// <summary>
/// Optional lazy data source. When implemented, the resolver publishes a
/// structure-only snapshot immediately (fast) and materializes each series
/// subtree on first access via GetSeriesData. Structure entries carry
/// series-level data only; their Mappings may be empty.
/// </summary>
public interface ILazyShokoPathDataSource
{
    /// <summary>Series-level layout: one SeriesData per series in scope, with empty (or partial) Mappings.</summary>
    IReadOnlyList<SeriesData> GetSeriesStructure();

    /// <summary>Full per-series data (Mappings + Extras) for one series. Adapters cache per series ID. Return null if the series has no data.</summary>
    SeriesData? GetSeriesData(int seriesId);

    /// <summary>Drop cached data for one series (or all when null). Next GetSeriesData refetches.</summary>
    void Invalidate(int? seriesId);
}

/// <summary>
/// A series and its pre-resolved episode/file mappings.
/// </summary>
/// <param name="SeriesId">The Shoko series identifier.</param>
/// <param name="DisplayTitle">The display title, if available.</param>
/// <param name="IsMovie">Whether the series entry represents a movie.</param>
/// <param name="Mappings">
/// Pre-resolved per-series episode/file mappings. These are SHOW entries at
/// series level, not database tables.
/// </param>
/// <param name="Extras">
/// Optional per-series extra files surfaced at the series-folder root (e.g.
/// <c>Theme.mp3</c> generated by ShokoRelay's AnimeThemes integration). Null
/// means "no extras known" — render nothing. <paramref name="Name"/> may carry
/// "/" segments to place the file inside a series-root subdirectory (e.g.
/// <c>Shorts/….webm</c>), mirroring upstream's AnimeThemes Shorts links which
/// land in the TV series folder and every standalone movie folder alike.
/// </param>
/// <param name="TvLocalExtras">
/// Plex local-extra subdirectory files discovered under the series' source
/// folders (upstream VfsAssetLinker.LinkLocalExtras). Rendered at the TV series
/// root only — never inside standalone movie folders. <paramref name="Name"/> is
/// series-root relative ("<c>Season 2/Behind The Scenes/x.mkv</c>").
/// </param>
public sealed record SeriesData(
    int SeriesId,
    string? DisplayTitle,
    bool IsMovie,
    IReadOnlyList<EpisodeData> Mappings,
    IReadOnlyList<ExtraFile>? Extras = null,
    IReadOnlyList<ExtraFile>? TvLocalExtras = null);

/// <summary>
/// A pre-resolved extra file associated with a series (AnimeThemes Theme.mp3
/// and similar non-Shoko assets) that should appear at the series-folder root
/// of the virtual filesystem.
/// </summary>
/// <param name="Name">The filename as it should appear in the VFS (e.g. <c>Theme.mp3</c>).</param>
/// <param name="SourcePath">The absolute source path on disk that FUSE reads will proxy to.</param>
/// <param name="Size">The source file size in bytes.</param>
public sealed record ExtraFile(string Name, string SourcePath, long Size);

/// <summary>
/// A local asset file that upstream's VfsAssetLinker links next to a video entry
/// (subtitle/image/NFO sidecars, <c>_attach</c> folder contents, Plex inline
/// extras). <paramref name="Suffix"/> is the destination-name remainder: the
/// resolver appends it to the video entry's VFS base name (name without
/// extension) so sidecar basenames always pair with the video's. For attachment
/// files the suffix starts with <c>_attach/</c> (upstream always renames the
/// source <c>_attach</c>/<c>_attachments</c> folder to <c>&lt;base&gt;_attach</c>).
/// </summary>
/// <param name="Suffix">Destination-name remainder appended to the video's VFS base name.</param>
/// <param name="SourcePath">Absolute source path on disk.</param>
/// <param name="Size">Source file size in bytes.</param>
public sealed record LocalAssetFile(string Suffix, string SourcePath, long Size);

/// <summary>
/// A pre-resolved mapping between a Shoko episode and its source file.
/// </summary>
/// <param name="FileId">The Shoko file identifier.</param>
/// <param name="EpisodeId">The primary Shoko episode identifier.</param>
/// <param name="Season">
/// The episode season coordinate. Negative seasons identify extras: -1 credits,
/// -2 trailers, -3 scenes, -4 featurettes, and -9 other extras.
/// </param>
/// <param name="Episode">The episode coordinate within the season.</param>
/// <param name="EndEpisode">The end of an episode range, or null for a single episode.</param>
/// <param name="PartIndex">The part index for a multi-part file, or null if not multi-part.</param>
/// <param name="PartCount">The number of parts for a multi-part file, or null if not multi-part.</param>
/// <param name="IsVariation">Whether this is a duplicate or variant file.</param>
/// <param name="IsMain">Whether this is a regular episode rather than an extra, intro, or similar entry.</param>
/// <param name="EpisodeTitle">The display title, used when naming extras.</param>
/// <param name="SourcePath">
/// The absolute resolved source path. Null means this mapping must be skipped.
/// </param>
/// <param name="Size">
/// The indexed source file size in bytes. This is metadata from Shoko and may
/// be stale; reading it does not access source storage.
/// </param>
/// <param name="Extension">The file extension with a leading dot, such as <c>.mkv</c>.</param>
/// <param name="Sidecars">
/// Local assets linked next to this mapping's video entry (subtitle/image/NFO
/// sidecars and <c>_attach</c> folder files) — upstream LinkEpisodeMetadata.
/// Rendered beside the video in the TV season folder and the standalone movie
/// folder alike. Null when none were discovered.
/// </param>
/// <param name="InlineLocalExtras">
/// Plex inline local-extra video files named <c>&lt;base&gt;-trailer.mkv</c> etc.
/// that are linked beside this mapping with the parent's VFS base name —
/// upstream LinkLocalExtras (TV pass only).
/// </param>
/// <param name="SeriesAssets">
/// Series-level local metadata/artwork files found in this mapping's source
/// folder (posters, fanart, logos, NFOs, <c>Theme.mp3</c>) — upstream
/// LinkSeriesMetadata. The resolver aggregates these at the TV series-folder
/// root and mirrors them into every standalone movie folder.
/// </param>
/// <param name="XrefSeriesIds">
/// Distinct Shoko series ids this file is cross-referenced to (episodes only).
/// Used during asset discovery to reproduce upstream's crossover gate.
/// </param>
/// <param name="SuppressTvLocalAssets">
/// True when this mapping's video is cross-referenced into more than one primary
/// series (upstream's <c>distinctPrimarySeriesCount &gt; 1</c> gate): the TV tree
/// renders neither its sidecars nor its folder's series assets. Standalone movie
/// folders are never gated.
/// </param>
public sealed record EpisodeData(
    int FileId,
    int EpisodeId,
    int Season,
    int Episode,
    int? EndEpisode,
    int? PartIndex,
    int? PartCount,
    bool IsVariation,
    bool IsMain,
    string? EpisodeTitle,
    string? SourcePath,
    long Size,
    string Extension,
    IReadOnlyList<LocalAssetFile>? Sidecars = null,
    IReadOnlyList<LocalAssetFile>? InlineLocalExtras = null,
    IReadOnlyList<ExtraFile>? SeriesAssets = null,
    IReadOnlyList<int>? XrefSeriesIds = null,
    bool SuppressTvLocalAssets = false);
