using Shoko.VFS.FUSE.Models;

namespace Shoko.VFS.FUSE.Resolvers;

/// <summary>
/// Supplies the pre-resolved Shoko data used by a path resolver.
/// Adapters are responsible for caching data returned by Shoko.
/// </summary>
public interface IShokoPathDataSource
{
    /// <summary>
    /// Gets all series and their episode/file mappings.
    /// Consumers that need mutable data may call this method again.
    /// </summary>
    IReadOnlyList<SeriesData> GetAllSeries();
}

/// <summary>
/// Optional lazy data source. When implemented, the resolver publishes a
/// structure-only snapshot immediately (fast) and materializes each series
/// subtree on first access via GetSeriesData. Structure entries carry
/// series-level data only; their Mappings may be empty.
/// </summary>
public interface ILazyShokoPathDataSource
{
    /// <summary>Series-level layout: one SeriesData per series in scope, with empty (or partial) Mappings.</summary>
    IReadOnlyList<SeriesData> GetSeriesStructure();

    /// <summary>Full per-series data (Mappings + Extras) for one series. Adapters cache per series ID. Return null if the series has no data.</summary>
    SeriesData? GetSeriesData(int seriesId);

    /// <summary>Drop cached data for one series (or all when null). Next GetSeriesData refetches.</summary>
    void Invalidate(int? seriesId);
}

/// <summary>
/// A series and its pre-resolved episode/file mappings.
/// </summary>
/// <param name="SeriesId">The Shoko series identifier.</param>
/// <param name="DisplayTitle">The display title, if available.</param>
/// <param name="IsMovie">Whether the series entry represents a movie.</param>
/// <param name="Mappings">
/// Pre-resolved per-series episode/file mappings. These are SHOW entries at
/// series level, not database tables.
/// </param>
/// <param name="Extras">
/// Optional per-series extra files surfaced at the series-folder root (e.g.
/// <c>Theme.mp3</c> generated by ShokoRelay's AnimeThemes integration). Null
/// means "no extras known" — render nothing.
/// </param>
public sealed record SeriesData(
    int SeriesId,
    string? DisplayTitle,
    bool IsMovie,
    IReadOnlyList<EpisodeData> Mappings,
    IReadOnlyList<ExtraFile>? Extras = null);

/// <summary>
/// A pre-resolved extra file associated with a series (AnimeThemes Theme.mp3
/// and similar non-Shoko assets) that should appear at the series-folder root
/// of the virtual filesystem.
/// </summary>
/// <param name="Name">The filename as it should appear in the VFS (e.g. <c>Theme.mp3</c>).</param>
/// <param name="SourcePath">The absolute source path on disk that FUSE reads will proxy to.</param>
/// <param name="Size">The source file size in bytes.</param>
public sealed record ExtraFile(string Name, string SourcePath, long Size);

/// <summary>
/// A pre-resolved mapping between a Shoko episode and its source file.
/// </summary>
/// <param name="FileId">The Shoko file identifier.</param>
/// <param name="EpisodeId">The primary Shoko episode identifier.</param>
/// <param name="Season">
/// The episode season coordinate. Negative seasons identify extras: -1 credits,
/// -2 trailers, -3 scenes, -4 featurettes, and -9 other extras.
/// </param>
/// <param name="Episode">The episode coordinate within the season.</param>
/// <param name="EndEpisode">The end of an episode range, or null for a single episode.</param>
/// <param name="PartIndex">The part index for a multi-part file, or null if not multi-part.</param>
/// <param name="PartCount">The number of parts for a multi-part file, or null if not multi-part.</param>
/// <param name="IsVariation">Whether this is a duplicate or variant file.</param>
/// <param name="IsMain">Whether this is a regular episode rather than an extra, intro, or similar entry.</param>
/// <param name="EpisodeTitle">The display title, used when naming extras.</param>
/// <param name="SourcePath">
/// The absolute resolved source path. Null means this mapping must be skipped.
/// </param>
/// <param name="Size">
/// The indexed source file size in bytes. This is metadata from Shoko and may
/// be stale; reading it does not access source storage.
/// </param>
/// <param name="Extension">The file extension with a leading dot, such as <c>.mkv</c>.</param>
public sealed record EpisodeData(
    int FileId,
    int EpisodeId,
    int Season,
    int Episode,
    int? EndEpisode,
    int? PartIndex,
    int? PartCount,
    bool IsVariation,
    bool IsMain,
    string? EpisodeTitle,
    string? SourcePath,
    long Size,
    string Extension);
